### ISSUE TITLE
org.jline.reader.UserInterruptException

### ISSUE THREAD

**Issue by strogiyotec** [strogiyotec/jfillin#10]
Let's catch UserInterruptException. How to reproduce?
1. Run jfill
2. Press Ctrl+C

Output
```
Exception in thread "main" org.jline.reader.UserInterruptException
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:702)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
	at jfill.InputHandler.getValue(InputHandler.java:27)
	at jfill.ValuesResolver.resolve(ValuesResolver.java:61)
	at jfill.Execution.execute(Execution.java:40)
	at jfill.Main.main(Main.java:33)
```

**Comment by strogiyotec** [comment]
Fixed in 2.1
