### ISSUE TITLE
Create file if not exist

### ISSUE THREAD

**Issue by strogiyotec** [strogiyotec/jfillin#11]
If XDG is not specified then the following error is occurred after execution
```
Exception in thread "main" java.nio.file.NoSuchFileException: /home/lolipop/jfillin/fillin.json
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.nio.file.Files.newOutputStream(Files.java:219)
        at java.nio.file.Files.write(Files.java:3422)
        at jfill.Cache.save(Cache.java:131)
        at jfill.ResolvedValuesStorage.flush(ResolvedValuesStorage.java:63)
        at jfill.Execution.execute(Execution.java:48)
        at jfill.Main.main(Main.java:33)
```

**Comment by strogiyotec** [comment]
Fixed in release 2.2
